# Generated by Django 2.0.4 on 2020-04-26 18:42

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_number', models.IntegerField()),
                ('boat_registration', models.CharField(max_length=250)),
                ('boat_image', models.FileField(upload_to='boats')),
            ],
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionshipPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship_position', models.IntegerField(null=True)),
                ('championship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Championship')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilots.Pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_points', models.IntegerField(null=True)),
                ('final_position', models.IntegerField(null=True)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Boat')),
                ('entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilots.Pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=250)),
                ('document_version', models.CharField(max_length=250)),
                ('document_link', models.CharField(max_length=250)),
                ('document_published', models.DateField(auto_now_add=True)),
                ('document_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EventBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=250)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_proposed_date', models.CharField(blank=True, max_length=250, null=True)),
                ('event_cover', models.FileField(upload_to='event-covers')),
                ('event_country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('event_description', models.TextField(null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('competitors', models.ManyToManyField(to='events.Competitors')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RaceLaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lap_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('boat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Boat')),
                ('championship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Championship')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilots.Pilot')),
                ('laps', models.ManyToManyField(to='events.RaceLaps')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.FileField(upload_to='sponsors')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='competitors',
            field=models.ManyToManyField(to='events.RaceResults'),
        ),
        migrations.AddField(
            model_name='race',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventBasic'),
        ),
        migrations.AddField(
            model_name='eventbasic',
            name='sponsors',
            field=models.ManyToManyField(to='events.Sponsors'),
        ),
        migrations.AddField(
            model_name='championship',
            name='events',
            field=models.ManyToManyField(to='events.EventBasic'),
        ),
        migrations.AddField(
            model_name='championship',
            name='pilot',
            field=models.ManyToManyField(to='pilots.Pilot'),
        ),
    ]
