# Generated by Django 2.0.4 on 2020-03-20 13:38

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200320_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbasic',
            name='event_country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
