# Generated by Django 2.0.4 on 2020-03-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventbasic_event_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbasic',
            name='event_description',
            field=models.TextField(null=True),
        ),
    ]
