# Generated by Django 2.0.4 on 2020-03-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0003_auto_20200320_1255'),
        ('events', '0005_auto_20200320_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Boat')),
                ('entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilots.Pilot')),
            ],
        ),
        migrations.AddField(
            model_name='eventbasic',
            name='competitors',
            field=models.ManyToManyField(to='events.Competitors'),
        ),
    ]
