# Generated by Django 2.0.4 on 2020-03-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200320_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitors',
            name='final_points',
            field=models.IntegerField(null=True),
        ),
    ]
