# Generated by Django 2.0.4 on 2020-03-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_competitors_final_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitors',
            name='final_position',
            field=models.IntegerField(null=True),
        ),
    ]
