# Generated by Django 2.0.4 on 2020-03-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_competitors_final_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbasic',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
