# Generated by Django 2.0.4 on 2020-03-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbasic',
            name='sponsors',
            field=models.ManyToManyField(to='events.Sponsors'),
        ),
    ]
