# Generated by Django 2.0.4 on 2020-03-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventbasic_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbasic',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
