# Generated by Django 2.0.4 on 2020-04-26 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalQuestionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=25)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_answers', models.ManyToManyField(to='pilots.MedicalQuestionAnswers')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilots.MedicalQuestionAnswers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilots.MedicalQuestions')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('dob', models.DateField(blank=True, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('bio', models.TextField(null=True)),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_image', models.FileField(null=True, upload_to='pilots/profile')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('display', models.BooleanField(default=True)),
                ('last_championship_position', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PilotLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.DateField()),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PilotMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('outcome', models.BooleanField(default=True)),
                ('signed_by', models.CharField(max_length=250)),
                ('signed_at', models.CharField(max_length=250)),
                ('signed_dob', models.DateField()),
                ('medical_file', models.FileField(upload_to='waiver')),
                ('questions', models.ManyToManyField(to='pilots.MedicalResults')),
            ],
        ),
        migrations.CreateModel(
            name='PilotWaiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_by', models.CharField(max_length=250)),
                ('signed_on', models.DateField(auto_now_add=True)),
                ('signed_at', models.CharField(max_length=250)),
                ('signed_location', models.CharField(max_length=250)),
                ('waiver_file', models.FileField(upload_to='waiver')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.CharField(max_length=250, null=True)),
                ('address_1', models.CharField(max_length=250, null=True)),
                ('address_2', models.CharField(max_length=250, null=True)),
                ('address_3', models.CharField(max_length=250, null=True)),
                ('postcode', models.CharField(max_length=250, null=True)),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pilots.Pilot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pilotlicense',
            name='medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilots.PilotMedical'),
        ),
        migrations.AddField(
            model_name='pilotlicense',
            name='waiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilots.PilotWaiver'),
        ),
    ]
