# Generated by Django 2.0.4 on 2020-03-19 12:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='nationality',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
            preserve_default=False,
        ),
    ]
