# Generated by Django 2.0.4 on 2020-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0003_auto_20200320_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
