# Generated by Django 2.0.4 on 2020-03-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0004_pilot_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='profile_image',
            field=models.FileField(null=True, upload_to='pilots/profile'),
        ),
    ]
