# Generated by Django 2.0.4 on 2020-03-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0005_auto_20200324_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilot',
            name='championship_position',
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='championships_entered',
        ),
    ]
