# Generated by Django 2.0.4 on 2020-03-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilots', '0006_auto_20200326_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='championship_position',
            field=models.IntegerField(null=True),
        ),
    ]
